// This file is part of the UnTech Game Engine.
// Copyright (c) 2016 - 2020, Marcus Rowe <undisbeliever@gmail.com>.
// Distributed under The MIT License: https://opensource.org/licenses/MIT


namespace Entities {
namespace BlankPlayer {
    buildFunctionTable(BasePlayerFunctionTable, BlankPlayer)

    a16()
    i16()
    code()
    Init:
    RoomAboutToChange:
    Process:
    DrawPlayer:
    ProcessCollision:
    function Null {
        rts
    }

}
}

// vim: ft=bass-65816 ts=4 sw=4 et:

