
// Temporary - will eventually be generated by a program

include "../../../src/common/registers.inc"

constant MetaTiles.N_TILES = 512

macro MT(char, pal, hFlip, vFlip) {
    variable t = {char} | ({pal} << Tilemap.palette.shift)
    if {hFlip} {
        t = t | Tilemap.hFlip
    }
    if {vFlip} {
        t = t | Tilemap.vFlip
    }
    dw  t
}

// top-left
    MT(0, 1, 0, 0)
    MT(1, 2, 0, 0)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(5, 1, 0, 0)
    MT(4, 1, 1, 0)
    MT(0, 1, 0, 0)
    MT(3, 1, 0, 1)
    MT(2, 1, 1, 1)
    fill (MetaTiles.N_TILES - 10) * 2

// top-right
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(1, 2, 1, 0)
    MT(4, 1, 0, 0)
    MT(5, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(2, 1, 0, 1)
    MT(3, 1, 0, 1)
    MT(0, 1, 0, 0)
    fill (MetaTiles.N_TILES - 10) * 2

// bottom-left
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(3, 1, 0, 0)
    MT(2, 1, 1, 0)
    MT(0, 1, 0, 0)
    MT(5, 1, 0, 0)
    MT(4, 1, 1, 0)
    MT(1, 2, 0, 1)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    fill (MetaTiles.N_TILES - 10) * 2

// bottom-right
    MT(0, 1, 0, 0)
    MT(2, 1, 0, 0)
    MT(3, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(4, 1, 0, 0)
    MT(5, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(0, 1, 0, 0)
    MT(1, 2, 1, 1)
    fill (MetaTiles.N_TILES - 10) * 2

